### ISSUE TITLE
Python 3.6.1 requirement

### ISSUE THREAD

**Issue by danpalmer** [domdfcoding/flake8-github-actions#15]
The plugin depends on Python 3.6.1, meaning that consumers wishing to use a dependency resolver such as that in Poetry will also need to require 3.6.1.

As most projects use some sort of semantic versioning, it's typical to specify dependencies as either X, or X.Y, and then let a lock-file of some sort pin to X.Y.Z. It is rare that a patch version is a necessary upgrade for a project.

Does `flake8-github-actions` depend specifically on 3.6.1? If not, I'd encourage this requirement to be loosened to 3.6 so that package consumers do not need to require 3.6.1 either, and enforce that strict requirement on _their_ consumers, and so on.

If the 3.6.1 requirement is necessary it would be great to get a better understanding of the edge case. Can it be documented? Is there a workaround that can be applied so that the version bounds can be loosened?

**Comment by domdfcoding** [comment]
Hi @danpalmer,

Thanks for opening this issue. 

The minimum version was set because `typing.NamedTuple` didn't support default values in 3.6.0, but as `flake8-github-actions` doesn't actually use `NamedTuple` it should work fine.
I have relaxed the version requirement to `>=3.6` and made a new release ([0.1.1](https://pypi.org/project/flake8-github-actions/0.1.1/)). Does that resolve your issue?
